##### import the Diamond dataset

In [1]:
import pandas as pd

In [2]:
diamonds_data = pd.read_csv('diamonds.csv')

diamonds_df = pd.DataFrame(diamonds_data)
diamonds_df

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75
...,...,...,...,...,...,...,...,...,...,...,...
53935,53936,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53936,53937,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53937,53938,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74
53939,53940,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64

###### 1. Write a Pandas program to find the number of rows and columns and data type of each column of diamonds Dataframe.

In [3]:
### code here

print('The Number of rows and columns are :',diamonds_df.shape)
print('\nData type of each column:')
diamonds_df.dtypes

The Number of rows and columns are : (53940, 11)

Data type of each column:

Unnamed: 0      int64
carat         float64
cut            object
color          object
clarity        object
depth         float64
table         float64
price           int64
x             float64
y             float64
z             float64
dtype: object

##### 2. Write a Pandas program to summarize only 'object' columns of the diamonds Dataframe.

In [4]:
### code here

diamonds_df.select_dtypes(include='object').describe()

          cut  color clarity
count   53940  53940   53940
unique      5      7       8
top     Ideal      G     SI1
freq    21551  11292   13065

###### 3. Write a Pandas program to remove the second column of the diamonds Dataframe. (don't use original dataset)

In [5]:
### code here

diamonds_df.drop(diamonds_df.columns[1], axis=1)

,Unnamed: 0,cut,color,clarity,depth,table,price,x,y,z
0,1,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75
...,...,...,...,...,...,...,...,...,...,...
53935,53936,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53936,53937,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53937,53938,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53938,53939,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74
53939,53940,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64

###### 4. Write a Pandas program to remove multiple rows at once (axis=0 refers to rows) from diamonds dataframe. (dont use original dataset)

In [6]:
### code here

diamonds_df.drop([1,3,5],axis=0)

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75
6,7,0.24,Very Good,I,VVS1,62.3,57.0,336,3.95,3.98,2.47
7,8,0.26,Very Good,H,SI1,61.9,55.0,337,4.07,4.11,2.53
...,...,...,...,...,...,...,...,...,...,...,...
53935,53936,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53936,53937,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53937,53938,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74
53939,53940,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64

###### 5. Write a Pandas program to sort the 'cut' Series in ascending order (returns a Series) of diamonds Dataframe.

In [7]:
### code here

diamonds_df['cut'].sort_values()

3850          Fair
51464         Fair
51466         Fair
10237         Fair
10760         Fair
           ...
7402     Very Good
43101    Very Good
16893    Very Good
16898    Very Good
21164    Very Good
Name: cut, Length: 53940, dtype: object

###### 6. Write a Pandas program to sort the entire diamonds DataFrame by the 'carat' Series in ascending and descending order.

In [8]:
### code here

diamonds_df.sort_values(by=['carat','carat'],ascending=[True,False])

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
14,15,0.20,Premium,E,SI2,60.2,62.0,345,3.79,3.75,2.27
31591,31592,0.20,Premium,E,VS2,59.8,62.0,367,3.79,3.77,2.26
31592,31593,0.20,Premium,E,VS2,59.0,60.0,367,3.81,3.78,2.24
31593,31594,0.20,Premium,E,VS2,61.1,59.0,367,3.81,3.78,2.32
31594,31595,0.20,Premium,E,VS2,59.7,62.0,367,3.84,3.80,2.28
...,...,...,...,...,...,...,...,...,...,...,...
25998,25999,4.01,Premium,I,I1,61.0,61.0,15223,10.14,10.10,6.17
25999,26000,4.01,Premium,J,I1,62.5,62.0,15223,10.02,9.94,6.24
27130,27131,4.13,Fair,H,I1,64.8,61.0,17329,10.00,9.85,6.43
27630,27631,4.50,Fair,J,I1,65.8,58.0,18531,10.23,10.16,6.72
27415,27416,5.01,Fair,J,I1,65.5,59.0,18018,10.74,10.54,6.98

###### 7. Write a Pandas program to filter the DataFrame rows to only show carat weight at least 0.3.

In [9]:
#### code here

diamonds_df[diamonds_df['carat']>=0.3]

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75
10,11,0.30,Good,J,SI1,64.0,55.0,339,4.25,4.28,2.73
13,14,0.31,Ideal,J,SI2,62.2,54.0,344,4.35,4.37,2.71
15,16,0.32,Premium,E,I1,60.9,58.0,345,4.38,4.42,2.68
16,17,0.30,Ideal,I,SI2,62.0,54.0,348,4.31,4.34,2.68
...,...,...,...,...,...,...,...,...,...,...,...
53935,53936,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53936,53937,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53937,53938,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74
53939,53940,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64

###### 8.  Write a Pandas program to find the details of the diamonds where length>5, width>5 and depth>5.

In [10]:
### code here 

diamonds_df[(diamonds_df['x']>5) & (diamonds_df['y']>5) & (diamonds_df['z']>5)]

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
11778,11779,1.83,Fair,J,I1,70.0,58.0,5083,7.34,7.28,5.12
13002,13003,2.14,Fair,J,I1,69.4,57.0,5405,7.74,7.70,5.36
13118,13119,2.15,Fair,J,I1,65.5,57.0,5430,8.01,7.95,5.23
13562,13563,1.96,Fair,F,I1,66.6,60.0,5554,7.59,7.56,5.04
13757,13758,2.22,Fair,J,I1,66.7,56.0,5607,8.04,8.02,5.36
...,...,...,...,...,...,...,...,...,...,...,...
27748,27749,2.00,Very Good,G,SI1,63.5,56.0,18818,7.90,7.97,5.04
27749,27750,2.29,Premium,I,VS2,60.8,60.0,18823,8.50,8.47,5.16
48410,48411,0.51,Very Good,E,VS1,61.8,54.7,1970,5.12,5.15,31.80
49189,49190,0.51,Ideal,E,VS1,61.8,55.0,2075,5.15,31.80,5.12
49905,49906,0.50,Very Good,G,VVS1,63.7,58.0,2180,5.01,5.04,5.06

###### 9. Write a Pandas program to calculate the mean of each row of diamonds DataFrame.

In [11]:
### code here

diamonds_df.mean(axis=1, numeric_only=True)

0          56.76125
1          57.38125
2          57.82000
3          58.71875
4          59.13125
            ...
53935    7103.31625
53936    7103.48375
53937    7104.17500
53938    7103.98375
53939    7103.78625
Length: 53940, dtype: float64

###### 10. Write a Pandas program to calculate the mean of price for each cut  and find maximum top 3 of diamonds DataFrame.

In [12]:
#### code here

diamonds_df.groupby('cut')['price'].mean().sort_values(ascending=False).head(3)

cut
Premium      4584.257704
Fair         4358.757764
Very Good    3981.759891
Name: price, dtype: float64

##### 11. Write a Pandas program to calculate count, minimum, maximum price for each cut of diamonds DataFrame.

In [13]:
### code here

diamonds_df.groupby('cut')['price'].agg(['count','min','max'])

           count  min    max
cut
Fair        1610  337  18574
Good        4906  327  18788
Ideal      21551  326  18806
Premium    13791  326  18823
Very Good  12082  336  18818

###### 12. Write a Pandas program to display and count the unique values in cut series of diamonds DataFrame.

In [14]:
### code here

print(diamonds_df['cut'].unique())

print(diamonds_df['cut'].nunique())

['Ideal' 'Premium' 'Good' 'Very Good' 'Fair']
5

###### 13.  Write a Pandas program to count the number of missing values in each Series of diamonds DataFrame.

In [15]:
### code here

diamonds_df.isnull().sum()

Unnamed: 0    0
carat         0
cut           0
color         0
clarity       0
depth         0
table         0
price         0
x             0
y             0
z             0
dtype: int64

###### 14. Write a Pandas program to calculate the multiply of x, y and z for each cut of diamonds DataFrame.

In [16]:
### code here

diamonds_df.groupby('cut').apply(lambda x: (x['x'] * x['y'] * x['z']).mean())

cut
Fair         164.950549
Good         136.257267
Ideal        115.394912
Premium      145.052128
Very Good    130.999722
dtype: float64

##### 15. Write a Pandas program to read rows 0 through 2 (inclusive), columns ‘color’ and ‘price’ of diamonds DataFrame.

In [17]:
## code here

diamonds_df.loc[0:2,['color','price']]

  color  price
0     E    326
1     E    326
2     E    327

###### 16. Write a Pandas program to read rows in positions 0 and 1, columns in positions 0 and 3 of diamonds DataFrame.

In [18]:
### code here

diamonds_df.iloc[[0,1],[0,3]]

   Unnamed: 0 color
0           1     E
1           2     E

##### 17. Write a Pandas program to get randomly sample rows from diamonds DataFrame.

In [19]:
### code here

diamonds_df.sample(frac=1,random_state=42).reset_index(drop=True)

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1389,0.24,Ideal,G,VVS1,62.1,56.0,559,3.97,4.00,2.47
1,50053,0.58,Very Good,F,VVS2,60.0,57.0,2201,5.44,5.42,3.26
2,41646,0.40,Ideal,E,VVS2,62.1,55.0,1238,4.76,4.74,2.95
3,42378,0.43,Premium,E,VVS2,60.8,57.0,1304,4.92,4.89,2.98
4,17245,1.55,Ideal,E,SI2,62.3,55.0,6901,7.44,7.37,4.61
...,...,...,...,...,...,...,...,...,...,...,...
53935,11285,1.05,Very Good,I,VS2,62.4,59.0,4975,6.48,6.51,4.05
53936,44733,0.47,Ideal,D,VS1,61.0,55.0,1617,5.03,5.01,3.06
53937,38159,0.33,Very Good,F,IF,60.3,58.0,1014,4.49,4.46,2.70
53938,861,0.90,Premium,J,SI1,62.8,59.0,2871,6.13,6.03,3.82
53939,15796,1.14,Premium,F,SI1,60.4,58.0,6320,6.82,6.79,4.11

###### 18. Write a Pandas program to get sample 75% of the diamonds DataFrame's rows without replacement and store the remaining 25% of the rows in another DataFrame.

In [20]:
### code here

diamonds_75 = diamonds_df.sample(frac=0.75,random_state=42).reset_index(drop=True)

print("75% Sample:")
diamonds_75.head()

75% Sample:

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1389,0.24,Ideal,G,VVS1,62.1,56.0,559,3.97,4.00,2.47
1,50053,0.58,Very Good,F,VVS2,60.0,57.0,2201,5.44,5.42,3.26
2,41646,0.40,Ideal,E,VVS2,62.1,55.0,1238,4.76,4.74,2.95
3,42378,0.43,Premium,E,VVS2,60.8,57.0,1304,4.92,4.89,2.98
4,17245,1.55,Ideal,E,SI2,62.3,55.0,6901,7.44,7.37,4.61

In [21]:
diamonds_25 = diamonds_df.drop(diamonds_75.index).reset_index(drop=True)

print("Remaining 25%:")
diamonds_25.head()

Remaining 25%:

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,40456,0.5,Ideal,H,SI1,62.2,57.0,1140,5.07,5.09,3.16
1,40457,0.5,Ideal,H,SI1,62.4,56.0,1140,5.07,5.09,3.17
2,40458,0.5,Ideal,H,SI1,62.1,58.0,1140,5.04,5.07,3.14
3,40459,0.5,Ideal,H,SI1,62.5,57.0,1140,5.06,5.08,3.17
4,40460,0.5,Ideal,H,SI1,62.0,56.0,1140,5.08,5.11,3.16

###### 19. Write a Pandas program to read the diamonds DataFrame and detect duplicate color.

In [22]:
#### code here

diamonds_df['color'].duplicated()

0        False
1         True
2         True
3        False
4        False
         ...
53935     True
53936     True
53937     True
53938     True
53939     True
Name: color, Length: 53940, dtype: bool

###### 20. Write a Pandas program to count the duplicate rows of diamonds DataFrame.

In [23]:
#### code here

diamonds_df.duplicated().sum()

0