In [1]:
import pandas as pd
import numpy as np
data  = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

##### Write a Pandas program to create a dataframe by given dictionary and index as labels

In [2]:
df = pd.DataFrame(data,index = labels)
df

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

##### 1. Write a Pandas program to select the rows where the score is missing, i.e. is NaN

In [3]:
### code here

df[df['score'].isna()]

    name  score  attempts qualify
d  James    NaN         3      no
h  Laura    NaN         1      no

##### 2. Write a Pandas program to change the score in row 'd' to 11.5.

In [4]:
### code here

df.loc['d','score'] = 11.5
df

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

##### 3. Write a Pandas program to select the 'name' and 'score' columns from the following DataFrame.

In [5]:
#### code here

df[['name','score']]

        name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James   11.5
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0

##### 4.  Write a Pandas program to calculate the mean score for each different student in DataFrame.

In [6]:
###  code here

df.groupby('name')['score'].mean()

name
Anastasia    12.5
Dima          9.0
Emily         9.0
James        11.5
Jonas        19.0
Katherine    16.5
Kevin         8.0
Laura         NaN
Matthew      14.5
Michael      20.0
Name: score, dtype: float64

##### 5. Write a Pandas program to append a new row 'k' to data frame with any value for each column. Now delete the row 'c' and return the original DataFrame.

In [7]:
### code here

df.loc['k'] = ['Agatha',17.5,2,'yes']
print('Appended row "k":')
print(df.loc['k'])
df.drop('c',inplace=True)
print('The dataframe after appending the "k" row and deleting the "c" row:')
df

Appended row "k":
name        Agatha
score         17.5
attempts         2
qualify        yes
Name: k, dtype: object
The dataframe after appending the "k" row and deleting the "c" row:

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
d      James   11.5         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes
k     Agatha   17.5         2     yes

#import the titanic dataset

In [8]:
titanic_data = pd.read_csv('titanic.csv')

titanic_df = pd.DataFrame(titanic_data)
titanic_df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,Unnamed: 15
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,NaN
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,NaN
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,NaN
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,NaN
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,NaN
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,NaN
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,NaN
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,NaN
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,NaN

##### 1. Write a Pandas program to create a Pivot table and find the total fare amount class wise, gender wise.

In [9]:
#### code here

pd.pivot_table(titanic_df,values='fare',index=['class','sex'],aggfunc = 'sum')

                    fare
class  sex
First  female  9975.8250
       male    8201.5875
Second female  1669.7292
       male    2132.1125
Third  female  2321.1086
       male    4393.5865

##### 2. Write a Pandas program to create a Pivot table and find survival rate by gender.

In [10]:
### code here

pd.pivot_table(titanic_df,values='survived',index='sex',aggfunc='mean')

        survived
sex
female  0.742038
male    0.188908

###### 3. Write a Pandas to create to find the total count no of people survived pclass wise, class wise and gender wise.

In [11]:
### code here

pd.pivot_table(
    titanic_df,
    values='survived',
    index=['pclass','class','sex'],
    aggfunc='sum'
    )

                      survived
pclass class  sex
1      First  female        91
              male          45
2      Second female        70
              male          17
3      Third  female        72
              male          47

###### 4. Write a Pandas program to create a Pivot table and calculate how many women and men were in a particular cabin class.

In [12]:
###  code here

pd.pivot_table(
    titanic_df,
    index='class',
    columns='who',
    aggfunc='size'
)

who     child  man  woman
class
First       6  119     91
Second     19   99     66
Third      58  319    114

##### 5. Write a Pandas program to count the number of missing values in each column.

In [13]:
#### code here

print('The number of missing values in each columns are:')
titanic_df.isnull().sum()

The number of missing values in each columns are:

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
Unnamed: 15    891
dtype: int64

##### 6. Write a Pandas program to replace null values with the value from the previous row or the next row in a given DataFrame.

In [14]:
### code here

#backward filling i.e. filling with the next known value
#titanic_df['deck'] = titanic_df['deck'].fillna(method="bfill")

#forward filling i.e. filling with the last known value
#titanic_df['deck'] = titanic_df['deck'].fillna(method="ffill")

#Backward fill after forward fill

titanic_df['deck'] = titanic_df['deck'].ffill().bfill()

In [15]:
titanic_df['deck'].isnull().sum()

0

###### 7. Write a Pandas program to replace nulls, with median or mean of the specified columns in a given DataFrame.

In [16]:
### code here

#filling the null values in 'age' column with median

titanic_df['age'] = titanic_df['age'].fillna(titanic_df['age'].median())

In [17]:
titanic_df['age'].isnull().sum()

0

###### 8. Write a Pandas program to select first 2 rows, 2 columns and specific two columns from the dataframe.

In [18]:
#### code here

print('The first 2 rows and 2 columns of the Titanic dataframe:')
print(titanic_df.iloc[0:2,0:2])
print('\nTwo specific columns from the dataframe:')
print(titanic_df[['who','alive']])

The first 2 rows and 2 columns of the Titanic dataframe:
   survived  pclass
0         0       3
1         1       1

Two specific columns from the dataframe:
       who alive
0      man    no
1    woman   yes
2    woman   yes
3    woman   yes
4      man    no
..     ...   ...
886    man    no
887  woman   yes
888  woman    no
889    man   yes
890    man    no

[891 rows x 2 columns]

###### 9. Write a Pandas program to remove the duplicates from 'embark_town' column of titanic dataset.

In [19]:
#### code here

titanic_df[~titanic_df['embark_town'].duplicated()]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,Unnamed: 15
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,C,Southampton,no,False,NaN
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,NaN
5,0,3,male,28.0,0,0,8.4583,Q,Third,man,True,C,Queenstown,no,True,NaN
61,1,1,female,38.0,0,0,80.0000,NaN,First,woman,False,B,NaN,yes,True,NaN

###### 10. Write a Pandas program to find out the survived is 1 details by the 'Southampton' in who is the 'child' from dataset.

In [20]:
### code here

titanic_df[
    (titanic_df['embark_town']=='Southampton') & 
    (titanic_df['who']=='child') & 
    (titanic_df['survived']==1)
    ]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,Unnamed: 15
10,1,3,female,4.00,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False,NaN
58,1,2,female,5.00,1,2,27.7500,S,Second,child,False,C,Southampton,yes,False,NaN
78,1,2,male,0.83,0,2,29.0000,S,Second,child,False,F,Southampton,yes,False,NaN
165,1,3,male,9.00,0,2,20.5250,S,Third,child,False,C,Southampton,yes,False,NaN
172,1,3,female,1.00,1,1,11.1333,S,Third,child,False,B,Southampton,yes,False,NaN
183,1,2,male,1.00,2,1,39.0000,S,Second,child,False,F,Southampton,yes,False,NaN
184,1,3,female,4.00,0,2,22.0250,S,Third,child,False,F,Southampton,yes,False,NaN
193,1,2,male,3.00,1,1,26.0000,S,Second,child,False,F,Southampton,yes,False,NaN
233,1,3,female,5.00,4,2,31.3875,S,Third,child,False,C,Southampton,yes,False,NaN
237,1,2,female,8.00,0,2,26.2500,S,Second,child,False,C,Southampton,yes,False,NaN
261,1,3,male,3.00,4,2,31.3875,S,Third,child,False,B,Southampton,yes,False,NaN
305,1,1,male,0.92,1,2,151.5500,S,First,child,False,C,Southampton,yes,False,NaN
340,1,2,male,2.00,1,1,26.0000,S,Second,child,False,F,Southampton,yes,False,NaN
348,1,3,male,3.00,1,1,15.9000,S,Third,child,False,F,Southampton,yes,False,NaN
407,1,2,male,3.00,1,1,18.7500,S,Second,child,False,G,Southampton,yes,False,NaN
435,1,1,female,14.00,1,2,120.0000,S,First,child,False,B,Southampton,yes,False,NaN
445,1,1,male,4.00,0,2,81.8583,S,First,child,False,A,Southampton,yes,False,NaN
446,1,2,female,13.00,0,1,19.5000,S,Second,child,False,A,Southampton,yes,False,NaN
479,1,3,female,2.00,0,1,12.2875,S,Third,child,False,A,Southampton,yes,False,NaN
489,1,3,male,9.00,1,1,15.9000,S,Third,child,False,B,Southampton,yes,False,NaN
530,1,2,female,2.00,1,1,26.0000,S,Second,child,False,C,Southampton,yes,False,NaN
535,1,2,female,7.00,0,2,26.2500,S,Second,child,False,C,Southampton,yes,False,NaN
549,1,2,male,8.00,1,1,36.7500,S,Second,child,False,C,Southampton,yes,False,NaN
618,1,2,female,4.00,2,1,39.0000,S,Second,child,False,F,Southampton,yes,False,NaN
689,1,1,female,15.00,0,1,211.3375,S,First,child,False,B,Southampton,yes,False,NaN
720,1,2,female,6.00,0,1,33.0000,S,Second,child,False,E,Southampton,yes,False,NaN
750,1,2,female,4.00,1,1,23.0000,S,Second,child,False,D,Southampton,yes,False,NaN
751,1,3,male,6.00,0,1,12.4750,S,Third,child,False,E,Southampton,yes,False,NaN
755,1,2,male,0.67,1,1,14.5000,S,Second,child,False,E,Southampton,yes,False,NaN
777,1,3,female,5.00,0,0,12.4750,S,Third,child,False,F,Southampton,yes,True,NaN
788,1,3,male,1.00,1,2,20.5750,S,Third,child,False,D,Southampton,yes,False,NaN
802,1,1,male,11.00,1,2,120.0000,S,First,child,False,B,Southampton,yes,False,NaN
831,1,2,male,0.83,1,1,18.7500,S,Second,child,False,B,Southampton,yes,False,NaN
869,1,3,male,4.00,1,1,11.1333,S,Third,child,False,A,Southampton,yes,False,NaN

###### 11. Write a Pandas program to filter all records starting from the 2nd row, access every 5th row from the dataframe.

In [21]:
### code here

titanic_df.iloc[2::5]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,Unnamed: 15
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,C,Southampton,yes,True,NaN
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,E,Southampton,no,False,NaN
12,0,3,male,20.0,0,0,8.0500,S,Third,man,True,C,Southampton,no,True,NaN
17,1,2,male,28.0,0,0,13.0000,S,Second,man,True,C,Southampton,yes,True,NaN
22,1,3,female,15.0,0,0,8.0292,Q,Third,child,False,D,Queenstown,yes,True,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
867,0,1,male,31.0,0,0,50.4958,S,First,man,True,A,Southampton,no,True,NaN
872,0,1,male,33.0,0,0,5.0000,S,First,man,True,B,Southampton,no,True,NaN
877,0,3,male,19.0,0,0,7.8958,S,Third,man,True,B,Southampton,no,True,NaN
882,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,C,Southampton,no,True,NaN
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,NaN

###### 12. Write a Pandas program to filter those records where embarked matches with multiple values (C, Q) from the dataset.

In [22]:
#### code here

titanic_df[
    (titanic_df['embarked']=='C') |
    (titanic_df['embarked']=='Q')
    ]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,Unnamed: 15
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,NaN
5,0,3,male,28.0,0,0,8.4583,Q,Third,man,True,C,Queenstown,no,True,NaN
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,E,Cherbourg,yes,False,NaN
16,0,3,male,2.0,4,1,29.1250,Q,Third,child,False,C,Queenstown,no,False,NaN
19,1,3,female,28.0,0,0,7.2250,C,Third,woman,False,C,Cherbourg,yes,True,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
875,1,3,female,15.0,0,0,7.2250,C,Third,child,False,B,Cherbourg,yes,True,NaN
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False,NaN
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,C,Queenstown,no,False,NaN
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,NaN
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,C,Queenstown,no,True,NaN